bluerabbit:
  outputs:
    prod_single:
      type: postgres
      threads: 1
      host: { { env_var('DB_HOST') } }
      port: "{{env_var('DB_PORT')}}"
      user: "{{env_var('DB_USER')}}"
      pass: "{{env_var('DB_PASS')}}"
      dbname: "{{env_var('DB_NAME')}}"
      schema: "{{env_var('DB_SCHEMA')}}"
    prod:
      type: postgres
      threads: 6
      host: { { env_var('DB_HOST') } }
      port: "{{env_var('DB_PORT')}}"
      user: "{{env_var('DB_USER')}}"
      pass: "{{env_var('DB_PASS')}}"
      dbname: "{{env_var('DB_NAME')}}"
      schema: "{{env_var('DB_SCHEMA')}}"
  target: prod
