bluerabbit:
  outputs:
    prod:
      type: postgres
      threads: 6
      host: "{{env_var('DB_HOST')}}"
      port: 5432
      user: "{{env_var('DB_USER')}}"
      pass: "{{env_var('DB_PASS')}}"
      dbname: "{{env_var('DB_NAME')}}"
      schema: "{{env_var('DB_SCHEMA')}}"
  target: prod
