{{
  config({
    "materialized": "table",
    "post-hook": [
      after_commit("create index  index_{{this.name}}_on_rxno on {{this.schema}}.{{this.name}} (rxno,refill_status)"),
      after_commit("create index  index_{{this.name}}_on_startdate on {{this.schema}}.{{this.name}} (start_date)")
      ]
  })
  }}
  select  
        patient_id,
        account_id,
        doctor_id,
        drug_id,
        last_tran_id,
        last_fill_number,
        last_dispense_date,
        rxno,
        no_of_refill,
        refill_status,
        rx_expire_date,
        days_supply,
        next_refill_date,
        nfo_status,
        schedule_type,
        start_date,
        previous_rxno,
        previous_rx_date,
        next_rxno,
        next_rx_date,
        nbr_renewals,
        prescription_renewal,
        opportunity_stage,
        opportunity_ranking,
        renewal_status,
        prescription_price,
        prescription_type,
        prescription_avg_price,
        actual_no_of_refill,
        over_prescribed,
        dispensed_refill_amount,
        dispensed_first_fill_amount,
        dispensed_total_amount,
        dispensed_refill_qty,
        dispensed_first_fill_qty,
        dispensed_total_qty,
        dispensed_nbr_refills,
        prescribed_refill_scheduled_amount,
        prescribed_refill_amount,
        prescribed_total_fill_amount,
        prescribed_refill_scheduled_qty,
        prescribed_refill_qty,
        prescribed_total_fill_qty,
        master_rxno,
        master_rx_start_date,
        origin,
        auto_fill,
        product_renewal,
        sig,
        flavor
        
from {{ ref('calc_refill_status') }}